# Generated by Django 3.1 on 2020-09-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_length',
            field=models.CharField(max_length=100),
        ),
    ]
