# Generated by Django 3.1 on 2020-09-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200905_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_length',
        ),
    ]
